### ISSUE TITLE
계좌 개설 페이지 제작

### ISSUE THREAD

**Issue by iamcharles98** [hee-ha/hana-heritage-FE#27]
## 작업 상세 내용
> 계좌 개설 페이지 제작

- [ ] 개설용 약관 동의 페이지
- [ ] 계좌 관련 정보 입력 페이지
- [ ] 가입 내용 확인 페이지
- [ ] 가입완료 페이지
- [ ] 디자인 디벨롭

**Comment by hyerimmy** [comment]
중복된 이슈로 close합니다.
